version: "3.0"

services:
  memcached:
    image: memcached
    restart: always
    expose:
      - "11211"

  otp-pass:
    image: phoenix916/otp-pass
    restart: always
    ports:
      - "80:80"
    command: "--memcached=memcached:11211 --port 80"
